export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_FAILURE = 'AJAX_CALL_FAILURE';

/* Authentication */
export const AUTHENTICATION_LOGIN = 'AUTHENTICATION_LOGIN';
export const AUTHENTICATION_LOGOUT = 'AUTHENTICATION_LOGOUT';
export const AUTHENTICATION_RESET_PASSWORD = 'AUTHENTICATION_RESET_PASSWORD';
export const AUTHENTICATION_CHANGE_PASSWORD = 'AUTHENTICATION_CHANGE_PASSWORD';
