export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_FAILURE = 'AJAX_CALL_FAILURE';

/* Authentication */
export const AUTHENTICATION_LOGIN_SUCCESS = 'AUTHENTICATION_LOGIN_SUCCESS';
export const AUTHENTICATION_LOGOUT_SUCCESS = 'AUTHENTICATION_LOGOUT_SUCCESS';
export const AUTHENTICATION_RESET_PASSWORD_SUCCESS =
	'AUTHENTICATION_RESET_PASSWORD_SUCCESS';
export const AUTHENTICATION_CHANGE_PASSWORD_SUCCESS =
	'AUTHENTICATION_CHANGE_PASSWORD_SUCCESS';

/* Users */
export const GET_USERS_BY_STATUS_SUCCESS = 'GET_USERS_BY_STATUS_SUCCESS';
export const GET_USER_BY_ID_SUCCESS = 'GET_USER_BY_ID_SUCCESS';
export const CREATE_USER_BY_INVITATION_SUCCESS =
	'CREATE_USER_BY_INVITATION_SUCCESS';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const ACTIVATE_USER_SUCCESS = 'ACTIVATE_USER_SUCCESS';

/* Profiles */
export const GET_PROFILES_BY_STATUS_SUCCESS = 'GET_PROFILES_BY_STATUS_SUCCESS';
export const GET_PROFILE_BY_ID_SUCCESS = 'GET_PROFILE_BY_ID_SUCCESS';
export const CREATE_PROFILE_SUCCESS = 'CREATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';

/* Utils */
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';
export const GET_SITEMAP_OPTIONS_SUCCESS = 'GET_SITEMAP_OPTIONS_SUCCESS';
