export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_FAILURE = 'AJAX_CALL_FAILURE';

/* Authentication */
export const AUTHENTICATION_LOGIN = 'AUTHENTICATION_LOGIN';
export const AUTHENTICATION_LOGOUT = 'AUTHENTICATION_LOGOUT';
export const AUTHENTICATION_RESET_PASSWORD = 'AUTHENTICATION_RESET_PASSWORD';
export const AUTHENTICATION_CHANGE_PASSWORD = 'AUTHENTICATION_CHANGE_PASSWORD';

/* Users */
export const GET_USERS_BY_STATUS = 'GET_USERS_BY_STATUS';
export const GET_USER_BY_ID = 'GET_USER_BY_ID';
export const CREATE_USER_BY_INVITATION = 'CREATE_USER_BY_INVITATION';
export const UPDATE_USER = 'UPDATE_USER';
export const ACTIVATE_USER = 'ACTIVATE_USER';

/* Profiles */
export const GET_PROFILES_BY_STATUS = 'GET_PROFILES_BY_STATUS';
export const GET_USERS_BY_STATUS_SUCCESS = 'GET_USERS_BY_STATUS_SUCCESS';
export const GET_PROFILE_BY_ID = 'GET_PROFILE_BY_ID';
export const CREATE_PROFILE = 'CREATE_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';

/* Utils */
export const UPLOAD_FILE = 'UPLOAD_FILE';
export const GET_SITEMAP_OPTIONS = 'GET_SITEMAP_OPTIONS';
